checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:    
        services:
            postgres: 13

        environment:
            php:
                version: 7.2.13
                
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php:
                    version: 7.2.13
                compile_options: '--enable-sigchild --without-pear'

                # see https://pecl.php.net/
                pecl_extensions:
                    - PDO_PGSQL
        
                pecl_extensions:
                    - sqlite3

            dependencies:
                override:
                    - composer --self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover   
                                          

