checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    environment:
        php:
            version: 7.2.13
            
    nodes:
        my-node:    
            services:
                postgres: 13
                
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php:
                    version: 7.2.13
                compile_options: '--without-pear'
        
                pecl_extensions:
                    - PDO_PGSQL

            dependencies:
                override:
                    - composer --self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover   
                                          

