checks:
    php: true

filter:
    paths:
        - "src/*"

tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600

build:
    environment:
        php: 7.4.12
        
    dependencies:
        override:
            - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
    tests:
        override:
            -
                command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                on_node: 1
                coverage:
                    file: coverage.xml
                    format: php-clover                    
    nodes:
        analysis:
            tests:
                override:
                    - 
                        php-scrutinizer-run
