checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    phpunit:
      services:
        db-mssql:
          image: mcr.microsoft.com/mssql/server:2019-latest

          # Define any additional environment variables that are needed by the service.
          env:
            SA_PASSWORD: YourStrong!Passw0rd
            ACCEPT_EULA: Y

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 1433

      tests:
        before:
          - docker exec -i db_mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'            