checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        php74:
            environment:
                php: 7.4.12
        
            dependencies:
                override:
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover      
                                          
        analysis:
            tests:
                override:
                    - 
                        php-scrutinizer-run
