checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    phpunit:
      environment:
        docker:
          remote_engine: true
          cache:
            images:
              - 'mcr.microsoft.com/mssql/server:2019-latest'
          
      tests:
        before:
          - docker run --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'" --health-interval=10s --health-timeout=5s --health-retries=3 -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrong!Passw0rd" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
          - docker ps -a
          - docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'         