build:
  environment:
    docker: 
      remote_engine: true
  project_setup:
    before:
      # Install SAM CLI
      - pip install aws-sam-cli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install

      # Configure AWS defaults
      - aws configure set aws_access_key_id scrutinizer_fake_key
      - aws configure set aws_secret_access_key scrutinizer_fake_secret
      - aws configure set default.region eu-west-1

      # Copy data to remote docker volume 
      - docker run -v /home/scrutinizer/build:/remote-host -d --name cp-container busybox
      - docker cp /home/scrutinizer/build/code cp-container:/remote-host/code

      # Start API and Lambda
      - command: sam local start-lambda -t cloudformation.yaml
        background: true  
  tests:
    override:
      - sam local invoke -t cloudformation.yaml "ProcessStream" --no-event