checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    environment:
        php: 7.4.12

    nodes:
        oracle:
            services:
                oci:
                    image: wnameless/oracle-xe-11g-r2:latest

                    ports:
                        - 1521

                    ramdisks:
                        - /var/lib/data   
                         
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:       
            dependencies:
                override:
                    - pecl install oci8-2.1.1
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover      
                                          

