checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  nodes:
    my-node:
      services:
        my-service:
          image: mysql:latest
          
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_PASSWORD: ''
            MYSQL_DATABASE: yiitest
