on:
  - pull_request
  - push

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php-version }}-${{ matrix.os }}
    env:
      extensions: ast, curl, mbstring, dom, intl, pdo, mysql, pdo_mysql
      key: cache-v1

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "7.4"
          - "8.0"

    steps:
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2     

      - name: Create project with composer php 7.4
        if: matrix.php-version == '7.4'
        run: composer create-project --prefer-dist --stability dev yii-extension/panel panel

      - name: Access directory panel
        if: matrix.php-version == '7.4'
        run: cd panel

      - name: Install codeception c3 coverage on Linux php 7.4
        if: matrix.os == 'ubuntu-latest' && matrix.php-version == '7.4'
        run: wget https://raw.github.com/Codeception/c3/2.0/c3.php

      - name: Run tests with codeception with coverage on Linux php 7.4
        if: matrix.os == 'ubuntu-latest' && matrix.php-version == '7.4'
        run: |
          php -S 127.0.0.1:8080 -t public > ./runtime/logs/yii.log 2>&1 &
          vendor/bin/codecept run --coverage --coverage-xml        