on:
  - pull_request
  - push

name: test

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      key: cache-v1

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - "7.4"
          - "8.0"

    steps:
      - name: View port linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo lsof -i -P -n

      - name: View port windows
        if: matrix.os == 'windows-latest'
        run: netstat -an
